
export const civNames = {
    aztecs: 'Aztecs',
    berbers: 'Berbers',
    britons: 'Britons',
    bulgarians: 'Bulgarians',
    burgundians: 'Burgundians',
    burmese: 'Burmese',
    byzantines: 'Byzantines',
    celts: 'Celts',
    chinese: 'Chinese',
    cumans: 'Cumans',
    ethiopians: 'Ethiopians',
    franks: 'Franks',
    goths: 'Goths',
    huns: 'Huns',
    incas: 'Incas',
    indians: 'Indians',
    italians: 'Italians',
    japanese: 'Japanese',
    khmer: 'Khmer',
    koreans: 'Koreans',
    lithuanians: 'Lithuanians',
    magyars: 'Magyars',
    malay: 'Malay',
    malians: 'Malians',
    mayans: 'Mayans',
    mongols: 'Mongols',
    persians: 'Persians',
    portuguese: 'Portuguese',
    saracens: 'Saracens',
    sicilians: 'Sicilians',
    slavs: 'Slavs',
    spanish: 'Spanish',
    tatars: 'Tatars',
    teutons: 'Teutons',
    turks: 'Turks',
    vietnamese: 'Vietnamese',
    vikings: 'Vikings'
};

export const civs = ['Aztecs','Berbers','Britons','Bulgarians', 'Burgundians', 'Burmese','Byzantines','Celts','Chinese','Cumans','Ethiopians','Franks','Goths',
'Huns','Incas','Indians','Italians','Japanese','Khmer','Koreans','Lithuanians','Magyars','Malay','Malians','Mayans','Mongols','Persians','Portuguese',
'Saracens', 'Sicilians', 'Slavs','Spanish','Tatars','Teutons','Turks','Vietnamese','Vikings'
];